###
GET http://localhost:8080/v1/ingredients/all

###
GET http://localhost:8080/v1/ingredients/FLTO

###
POST http://localhost:8080/v1/ingredients/add
Content-Type: application/json

{
  "id": "#TST",
  "name": "Test",
  "type": "WRAP"
}
###

PUT http://localhost:8080/v1/ingredients/FLTO
Content-Type: application/json

{
"id": "FLTO",
"name": "Test",
"type": "WRAP"
}